### ISSUE TITLE
Publish it to npm

### ISSUE THREAD

**Issue by mohsen1** [forms-js/forms-js#13]
I need to know under what name this is going to be published in npm so I can depend on it in web component repo

**Comment by bvaughn** [comment]
forms-js would probably be my pick

**Comment by mohsen1** [comment]
it's taken :(

**Comment by bvaughn** [comment]
Shit. Hmm.... well maybe something like forms-js-lib or forms-js-base?

**Comment by kentcdodds** [comment]
Maybe they'll give it to us...?
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by bvaughn** [comment]
Actually let's reach out to the author. He's only done 1 thing, 6 months
ago, so maybe he's no longer interested in that pacakge?

On Fri, Mar 13, 2015 at 12:38 AM, Mohsen Azimi notifications@github.com
wrote:

> it's taken :(
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/forms-js/forms-js/issues/13#issuecomment-78796055.

## 

Thanks,
Brian Vaughn
p. 540-246-5223

**Comment by bvaughn** [comment]
I'll email them and CC you guys

**Comment by bvaughn** [comment]
So good news here is that @parroit has agreed to unpublish the current forms-js NPM package so that we can use it for forms-js. Soon as Andrea has had the chance to do that, I'll publish a 0.0.1 version of the library for the ongoing adapter projects to use.

**Comment by bvaughn** [comment]
PS. In the meanwhile I've registered the Bower `forms-js` package.

**Comment by mohsen1** [comment]
Oh you published `forms-js` for `git://github.com/forms-js/forms-js.git`? I thought we're planning to publish bower with another repo. Is it possible to change the repo for bower?

**Comment by bvaughn** [comment]
I did not realize we were _planning_ on doing that, only discussing possibilities. If we decide to go that route, we can unregister the Bower package. I wanted to claim it for now though so it didn't get taken.

**Comment by bvaughn** [comment]
Closing this since we're published to NPM.
