### ISSUE TITLE
Git Ignore dist/

### ISSUE THREAD

**Issue by mohsen1** [forms-js/forms-js#14]
Having `dist/` in repo is harmful for source control. We have build as a `prepublish` hook so it's impossible to publish to npm without building first (btw we should have a test hook there too).

In [SwaggerUI](https://github.com/swagger-api/swagger-ui) we have dist checked in and I hate it every single diff!

**Comment by kentcdodds** [comment]
I recommend ghooks for git commit hooks :-) https://github.com/gtramontina/ghooks

**Comment by kentcdodds** [comment]
Though I must say that most projects I've seen do have the `dist/` in the repo. There are several reasons this is useful and I've never had a problem with putting the `dist/` in source control for libraries. If there's a conflict, just choose one or the other to merge and re-run the build.

**Comment by bvaughn** [comment]
I also dislike have the artifacts in Git next to the source but I was under the impression that it was necessary if we are to support NPM and Bowes.

**Comment by bvaughn** [comment]
*Bower

Sorry, commenting from my mobile

**Comment by mohsen1** [comment]
Although conflicts are an issue but that's not the main issue. Main issue is, dist makes reading diffs harder. There is duplicate code (source that changes and also the dist file). Specially that we use TypeScript, people might get confused when seeing a diff. In SwaggerUI sometime I comment on dist files instead of source when reviewing PRs.

**Comment by mohsen1** [comment]
@bvaughn You're right, Bower uses the git repo. Hmm... 

Is there any practical solution for this?

**Comment by bvaughn** [comment]
Not that I am aware of, although I would welcome one ;)

**Comment by mohsen1** [comment]
An ugly solution is to use another branch for development and keep dist in master but that's meh...

**Comment by kentcdodds** [comment]
Yes, there's a solution.

NPM: When you publish, it's publishing your local copy, so as long as you run the build and the `dist/` lives in there then you're fine

Bower: You commit to a tag, so perhaps we could have a build step that removes the .gitignore, runs the build, creates the tag, and re-adds the .gitignore.... o_O

I had a contributor on one of my projects make a PR to the `dist/` which was a little frustrating for both of us, so I get the issues with the `dist/` directory. Diffs are also a bit of an annoyance. But it's never been a big deal for me.

**Comment by kentcdodds** [comment]
The solution the angular team has is they have a different repo for bower. Not sure what they do for npm.

**Comment by mohsen1** [comment]
Another repo for Bower isn't too bad. It can be all automated so it's setup and forget kind of thing

**Comment by bvaughn** [comment]
The only word of caution I'd offer about that approach is that it will be nice if we keep things simple for local testing. For instance, a nice part about working with a `dist` directory in the same repo as source is that it makes it easy for you to do things like `gulp build && npm link` to test local changes. This would be particularly handy if we're working with a core lib like Forms JS and then several satellite libraries. (Not saying this couldn't be done differently, just that we should think about this use-case.)

**Comment by kentcdodds** [comment]
I say just keep dist
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by mohsen1** [comment]
@bvaughn ignoring in Git doesn't mean ignoring in npm. You can `npm link` if you clone this repo and link it.

**Comment by bvaughn** [comment]
Right, sorry. I was speaking to the comment about creating a separate Git repo and a script that build and committed to it.

**Comment by mohsen1** [comment]
Well, if we perfectly mirror `dist/` in that only-for-bower repo then for development we really don't need to clone the only-for-bower repo. We can simply `cd` into `dist` and `bower link`.

npm isn't an issue from what I understand since we can push dist to npm register

**Comment by bvaughn** [comment]
Sure. I wasn't saying it was _impossible_ just less _convenient_ if we had separate repos.

**Comment by mohsen1** [comment]
Case on point, see this commit:

1ca34b13d44b1e33dd03f09f3481ef3790edc4cb

**Comment by bvaughn** [comment]
I understand that having the `dist` in Git isn't ideal with regard to diffs. I also admit that it's generally unadvisable to store artifacts/binaries in version control. However...there is fairly strong precedent for this within the JavaScript community, thanks in part to Bower. I'd also argue that it's fairly easy to ignore the `dist` directory portion of a commit (or pull request) but I guess that's subjective.

Back to the community aspect... my main concerns are that:
- We don't do anything that will cause pain for contributors (not necessarily us) to do local development.
- We don't do anything that causes confusion to your average JavaScript developer.

In both of the above regards, I think a single repository with a `dist` folder included is preferable. It's the least "surprising" thing. If I'm a developer considering to use Forms JS- I know where to look. There's exactly one Github repository and exactly one place to file issues or requests. If I'm a contributor, it's straight forward to check out the library, build it, and test it locally.

Those are my main concerns.

**Comment by mohsen1** [comment]
Lets vote on this. I am strongly against storing dist in Github. Down the road it will cause a lot of confusion. People will make PR to dist folder or comment on dist changes and so on. It's not only a matter of _nicer_ looking diffs.

**Comment by bvaughn** [comment]
My vote is probably obvious. All of the projects I've worked on have included `dist` in the past and it hasn't caused problems.

**Comment by davidlgj** [comment]
I like having a dist/ folder in the repo as well. We have it in schema form
and it doesn't bother me.

Edit: We had in the beginning lot of PR's that included `dist` which caused some manual merging from my part, but I often merge manually anyway since I like to test the changes out myself. Also after adding a `CONTRIBUTING.md` that sorted itself out, and often enough its easy to ask people to remove the dist from their PR.

**Comment by kentcdodds** [comment]
My vote is keep the `dist` directory. For many of the same reasons that @bvaughn suggested. The drawbacks are minimal and the effort involved is less. Also I personally really like being able to look at a repo and know that it's more or less what would be installed if I npm installed it.

**Comment by mohsen1** [comment]
ok closing this ticket per votes. :)
