### ISSUE TITLE
Enable TravisCI

### ISSUE THREAD

**Issue by mohsen1** [forms-js/forms-js#19]
I'm getting a 500 error in TravisCI dashboard when I try enabling TravisCI for this project. It's in weird state where it's _off_ in "Add a new project" page but I can change settings in it's own [settings page](https://travis-ci.org/forms-js/forms-js/settings).

In terms of permissions we have the same level of permissions. We are both **owner** of the project so you should have permission to enable TravisCI for this project.

@bvaughn Please give it a shot and see if you're getting a 500 too. (check your browser network panel when enabling it.

![screen shot 2015-03-22 at 4 58 48 pm](https://cloud.githubusercontent.com/assets/543633/6772189/1523ed22-d0b5-11e4-89c6-83fcdb832222.png)

**Comment by bvaughn** [comment]
Unfortunately I can't even see it to try enabling it.

For example, I can load the [settings page](https://travis-ci.org/forms-js/forms-js/settings) but it's empty:
![screen shot 2015-03-22 at 5 12 18 pm](https://cloud.githubusercontent.com/assets/29597/6772225/24e92122-d0b6-11e4-938d-d7847dac942c.png)

I have no idea how to access the _Repositories_ page you're showing above. My _Repositories_ page has only my personal projects:
![screen shot 2015-03-22 at 5 13 49 pm](https://cloud.githubusercontent.com/assets/29597/6772234/571ff490-d0b6-11e4-8972-61e7e64d181d.png)

I was assuming you were some kind of special admin as far as Travis was concerned.

**Comment by mohsen1** [comment]
When I click **+** button I see all my orgs on right side. Have you tried clicking "Sync now" and see if forms-js org shows up?

![screen shot 2015-03-22 at 6 12 04 pm](https://cloud.githubusercontent.com/assets/543633/6772592/0d6ab412-d0bf-11e4-910b-7c9dd44cba33.png)

**Comment by bvaughn** [comment]
Yes, tried syncing but it doesn't resolve the issue.

**Comment by bvaughn** [comment]
Got it.

**Comment by bvaughn** [comment]
Travis is running our first build now. I had to go into my Github profile's [Authorized Applications](https://github.com/settings/applications) section and manually grant Travis the permission to see that I was a member of forms-js.

**Comment by mohsen1** [comment]
👏
