### ISSUE TITLE
Add better validation-schema support for collections

### ISSUE THREAD

**Issue by bvaughn** [forms-js/forms-js#20]
Forms JS currently supports collection validation by type (e.g. `type: "array"`), required, and min/max. However there is no agreed-upon format for validating objects within an array.

Let's say we have a collectin, "foo", that contains objects:

``` js
var formData = {
  foo: [
    {bar: "baz"}
  ]
};
```

We may want to validate `foo` as a collection (e.g. it must contain at least 2 items) as well as the items within foo (e.g. `bar` is a required field of type "string").

After some initial discussion with @mohsen1, here are 2 options we could consider.
### Option 1: Explicitly storing nested fields in an `items` key

``` js
var validationRules = {
  foo: {
    type: "array",
    min: 2,
    items: { // JSON Schema uses "items" for nested Array properties.
      bar: {
        type: "string",
        required: true
      }
    }
  }
}
```
### Option 2: Prefix our validation rules with an underscore

See issue #21 for more backgound information.

If we prefixed our validation attributes with an underscore, then validation rules for arrays with nested objects could look like this:

``` js
var validationRules = {
  foo: {
    _type: "array",
    _min: 2,
    bar: {
      _type: "string",
      _required: true
    }
  }
}
```

**Comment by bvaughn** [comment]
Progress made on a few fronts:
- a9122b0: Updated Flatten (and its tests) to better handle Arrays.
- 2408372: Added collections-support into type and min/max validators (and their tests). Also added strings messages for these new failure types.
- d609e64: Added unit tests for `AttributeMetadata`, `RequiredValidator`, and `ValidationService`. Fixed some edge-cases with values that have no validation rules (but still exist within the form).

**Comment by bvaughn** [comment]
Ping @mchapman, @mohsen1, @davidlgj, @kentcdodds

Sorry to bother you all directly like this, but I'd love to get your feedback regarding the 2 collection schema formats shown in this ticket's description. Do you think we should...
1. Mimic JSON schema and use an `items` key for nested attributes.
2. Prefix our attributes with "_" to disambiguate and eliminate the unnecessary key.
3. Something else...

I suppose I'm currently leaning slightly towards option 1.

**Comment by mchapman** [comment]
Option 1 was (apart from the choice of property names) what it said in the drive doc.  It made sense to me then and I can't see a reason to change my mind.

**Comment by bvaughn** [comment]
The design doc was kind of a _pitch_ but I don't recall _explicitly discussing_ collections. Seemed worth doing so since it has the potential to have a major impact on the library is all. :)

So that's a vote for option 1. :)

**Comment by bvaughn** [comment]
b3c5066: Added support for mapping nested array items (e.g. "addresses[0].street") to their corresponding validation rules (e.g. "addresses.items.street"). Also added tests for this and for the `Form` class.

**Comment by bvaughn** [comment]
This ticket may be done. Time will tell, as we move forward with the adapters and I write more unit tests.
