### ISSUE TITLE
Prefix validation rule attributes with "$" or "_" ? in order to better support collections

### ISSUE THREAD

**Issue by bvaughn** [forms-js/forms-js#21]
I'd like to discuss the possibility of prefixing our attributes (e.g. required, min/max, pattern, etc.) with '$' or '_' to avoid potentially conflicting with form data attributes. I can imagine cases where our validation keys may exist in the form data as well. So for example, let's pretend this is a form for bidding on an auction item or something...

``` js
var formData = { current: 100.00, max: 150.00, increment: 10.00 };

var validationRules = {
  current: { required: true, type: 'float' },
  max: { required: true, type: 'float' },
  increment: { required: true, type: 'float', min: 1.0 }
};
```

Is "max" a rule or is max a form data attribute that contains rules? This wouldn't currently cause a problem in Forms JS because we're relying on fields to explicitly register themselves with the `Form` (e.g. 'current', 'max,' and 'increment' fields would each be registered via `Form.registerAttribute`). But requiring fields to register themselves leads to a bit of awkwardness with collections: what registers the collection?

In my form-for library a special `collectionLabel` directive is provided to register collections. We may actually want something similar for Forms JS, because it gives us an obvious place to display errors with the collection itself (e.g. 3 items are required by the form only contains 2). But I wonder if it's a drawback that our current approach to validations _explicitly requires_ this?

Let's say for argument's sake that we decide to prefix validation rules with an underscore. Here's another hypothetical form data and validation ruleset:

``` js
var formData = {
  numbers: [
    {name: "Home", value: '123-123-1234'},
    {name: "Jenny's", value: '000-867-5309'}
  ]};

var validationRules = {
  numbers: {
    _type: 'array',
    _min: 1,
    name: {
      _type: 'string',
      _required: true
    },
    value: {
      _type: 'string',
      _required: true,
      _pattern: /^(\d )*\d{3}-\d{3}-\d{4}$/
    }
  }
};
```

This syntax may look a little less clean but it's also very explicit regarding what pertains to the _structure_ of the form data versus the _validation requirements_ of the data.

It also potentially frees us from requiring explicit field registration. Say for example that someone wrote the form markup and forgot to include a collections label for these numbers. We could still iterate the validation rules, looking for special keys that begin with "_", and validate the fact that the form requires at least one "numbers" object. The potential downsides of this approach are:
1. Where do we display validation errors for a field that hasn't been explicitly registered?
2. Are we breaking an important use-case of validating only a subset of fields within a larger, shared validation rules object?

This topic seems worth discussing. I feel conflicted at the moment.

**Comment by davidlgj** [comment]
We could also go the other way, a special prefix for any field with the same name as validation,
i.e. something like `_max` when you really mean the attribute field and not the validation.

**Comment by bvaughn** [comment]
True...although to me that is more confusing and ambiguous. (We'd have to always check for the presence of both to determine which we should use when looking up a field value.)

After thinking on this while at lunch, and some chatter here and in our Gitter room, I'm starting to think the auto-validation portion of this is not a good idea. Which makes me think that maybe none of the ideas discussed in this issue are necessary.

For example, if we have the following form-data object:

``` js
var formData = {
  required: boolean,
  min: {
    foo: "bar"
  }
};
```

It would be validated with the following validation rules:

``` js
var validationRules = {
  required: {
    type: "boolean",
    required: true
  },
  min: {
    foo: {
      type: "string",
      required: true
    }
  }
};
```

And then the following markup:

``` html
<checkbox-field name="required"></checkbox-field>
<text-field name="min.foo"></text-field>
```

I suppose the fact that the names overlap wouldn't _actually_ be a problem.

**Comment by bvaughn** [comment]
For clarity, the only thing it _really_ makes nicer is (arguably) the case of collections with nested object validations (as shown above).

**Comment by bvaughn** [comment]
This issue really boils down to the collections syntax, so I'm going to close this ticket in favor of #20.
