### ISSUE TITLE
Should we add faux-generics support for collections?

### ISSUE THREAD

**Issue by bvaughn** [forms-js/forms-js#22]
Forms JS currently supports:
- Array type `type: array`
- Basic validations on the array (`required`, `min`, `max`)
- Validations on nested objects within the array

However we don't support validating an arrays contents if those contents are primitives (e.g. we don't allow you to say "an array of numbers" vs "an array of strings").

We could support this using generics type syntax: `type: 'Array<String>'` if we think the use-case is important.

We could also support this by adding a new validation rule for arrays that worked something like:

``` js
validationRules = {
  someField: {
    type: 'Array',
    itemType: 'String' // String, Float, Boolean, Integer, Object
  }
};
```

This might be more inline with our other validation rules.

**Comment by mohsen1** [comment]
I like to keep the `type` property consistent in primitives too. It's a bit verbose but gives you the opportunity to add more stuff in the object.

``` js
validationRules = {
  someField: {
    type: 'Array',
    itemType: { type: 'string' }
  }
};
```

``` js
validationRules = {
  someField: {
    type: 'Array',
    itemType: {
      type: 'string',
      format: '[a-z]'
    }
  }
};
```

We're on the path of re-inventing JSON Schema! ;)

**Comment by bvaughn** [comment]
I don't think we're reinventing JSON schema. Just discussing how much of a subset of its functionality we also may want to support.

I don't like `itemType` being an object. I think the only _objects_ inside of validation rules should be the ones that mirror the structure of the form-data object. I'm also not necessarily convinced we even need to support this use-case. It could be done simply by letting users provide a custom validator for the collection like so:

``` js
validationRules = {
  someField: {
    type: 'Array',
    validators: [
      function(value, formData) {
        // Iterate over 'value' and do whatever you want to evaluate your primitive types
      }
    ]
  }
};
```

Maybe that's the better approach (at least for now) to keep things from getting to complex or special-cased.

**Comment by bvaughn** [comment]
Based on chatter in the Gitter room I'm going to close this issue for now. We can rely on custom validators for arrays of primitive types. If this becomes a feature people are really wanting in the future, we can always revisit. :)
