### ISSUE TITLE
Support overriding default validation failure messages

### ISSUE THREAD

**Issue by bvaughn** [forms-js/forms-js#4]
Forms JS provides default validation failure messages. Users should be able to override these defaults (for all Forms JS forms) in addition to overriding them on a per-field basis. This allows users with localization (or other) concerns to use Forms JS without manually overriding many fields.

formFor does this by providing a [configuration service](http://rawgit.com/bvaughn/angular-form-for/master/dist/docs/FormForConfiguration.html) but Forms JS does not have to follow this pattern. So long as some method of overriding error messages is available we should be okay.

**Comment by davidlgj** [comment]
I agree that we need a global configuration, but when dealing with single page apps it is also very nifty to be able to configure defaults _for one form_, and then override specific fields as well (as you allowed in your validation interface).

**Comment by bvaughn** [comment]
Ah, so you're saying we should support the use-case of multiple forms, each with their own set of default error messages (but not necessarily at the per-field level)?

**Comment by kentcdodds** [comment]
Global config is really nice. But we need to be careful because we should
consider the use case that someone will make a library of forms/controls
that others will use in combination with their own forms/controls or other
libraries and we just need to be considerate of the fact that these global
configs can alter behavior in unexpected ways for these libraries.

-Kent C. Dodds

**Comment by bvaughn** [comment]
In the case Kent's describing, I assume the decorating library would use Forms JS's configuration service to adjust messages as necessary (rather than exposing it to the end user). Perhaps I'm misunderstanding?

**Comment by kentcdodds** [comment]
I think you're understanding. I just don't want to get into a situation
where one library's global config conflicts with another's which conflicts
with my own. So we should use global config where it makes sense and
instance config everywhere else.

-Kent C. Dodds

**Comment by bvaughn** [comment]
Sure, I think part of the issue here is terminology. "Global" is a distasteful word, kind of like "singleton". All I meant was that Forms JS should provide some service to users by which users can customize the default form validation error messages. These messages should also be customizable on a per-field, per-failure basis (which they are). Perhaps additionally, they should be customizable on a per-form basis. I'd still like @davidlgj to elaborate a bit more on that use-case.

I don't think this approach should interfere with anyone else's libraries or locale configs.

**Comment by kentcdodds** [comment]
Ah, I think I misunderstood. That sounds great. :-)

-Kent C. Dodds

**Comment by bvaughn** [comment]
No problem. I've updated the description of this issue to hopefully be a little more clear. :)

**Comment by davidlgj** [comment]
@bvaughn Ok, let me elaborate a bit. Basically three levels would be nice. 
1. On "global" level, changing these changes the entire app. 
2. On instance level
3. On field level

So what I meant was that I wanted an "instance" level as well :) The use case being that in a larger single page app you might have several types/groups of form that require slightly different wording on validation messages on different pages/views. 

But it's not a super important thing since you can get it by overriding field validation messages, it's just that I have been bitten before by "global" options in single page apps when find yourself wanting different global options on different pages.

**Comment by bvaughn** [comment]
I like this suggestion. Let's do it!

**Comment by kentcdodds** [comment]
js-data does this and it's a terrific API. Maybe @jmdobry could give us
some tips on dealing with cascading options like that... @jmdobry, any
things to look out for or good methods you've come up with for making that
api so slick?

-Kent C. Dodds

**Comment by jmdobry** [comment]
It's all in the prototype. Global defaults are prototype properties of a `Defaults` class. Settings can be overridden globally by attaching overriding "own" properties to the `defaults` instance of `Defaults`. Instances in your lib, upon creation, set the `defaults` instance as their prototype. Settings can be overridden per instance by setting overriding "own" properties on an instance. During a method call, wrap the `options` object with a constructor function that uses the `instance` as its prototype. Settings can be overridden per method call by setting overriding "own" properties on the `options` hash.

So:

`Defaults` class (prototype properties) - Global defaults
`defaults` instance - (own properties) - Global overrides
`Instance` class (inherits from `defaults` via prototype) - Instance defaults
`instance` instance (own properties) - Instance overrides
`Options` class (inherits from `instance` via prototype) - Method defaults
`options` instance (own properties) - Method overrides

Some of these constructor functions (classes) will be repeatedly defined at runtime.

**Comment by bvaughn** [comment]
Thanks for the insight Jason (and for the intro Kent). This is an elegant approach. I think a similar approach will work well for validation messages.

**Comment by bvaughn** [comment]
Resolved via pull request #15

**Comment by bvaughn** [comment]
Forms JS library now has a `Strings` class.
- The prototype of this class defines an initial set of validation failure messages. (These are our global defaults).
- Override these prototype properties to globally change defaults for all of your forms.
- Instantiating `Strings` creates an instance that copies values from its prototype. (This includes any global overrides you may have set.)
- Override properties on your `Strings` instance to further customize for a _specific form_.
- Lastly, individual fields can provide overrides as always.

Thanks again to @jmdobry for the suggestions above!
